import React from 'react';
// Import the StateContext provider
import { StateContext } from '@/context/StateContext'; // Adjust the import path if necessary
import './globals.css'; // Your global CSS file

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  console.log('Rendering Layout');
  return (
    <div>
      <StateContext>
        {children}
      </StateContext>
    </div>
  );
}

