import React from 'react';
// Import the StateContext provider
import { StateContext } from '@/context/StateContext'; // Adjust the import path if necessary
import './globals.css'; // Your global CSS file

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <StateContext>
          {children}
        </StateContext>
      </body>
    </html>
  );
}
